name: Crawl Truyen Data

on:
  schedule:
    - cron: '0 0 * * *'  # Chạy hàng ngày vào lúc 00:00 UTC
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 requests

    - name: Run crawler
      run: python crawl_truyen.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add truyen_data.json
        git commit -m "Auto update truyen data"
        git push
